Promise.resolve("test").catch(console.error);

Promise.reject("test").catch(console.error);
